#!/usr/bin/env node
/* Drive the Stealth Science trio on a real origin, or on a local mount shaped
 * like one — the live leg's browser half.
 *
 * WHY THIS IS A SEPARATE FILE
 * ---------------------------
 * tools/verify_stealth_browser.mjs is the merge gate for built bytes: it
 * assembles its own local server and proves the build. This file proves the
 * DEPLOYMENT: same pages, fetched from whatever base it is pointed at —
 * https://madebymatt.uk in CI, a local mount when rehearsing — plus the two
 * pieces of coverage that exist nowhere else and were ordered for the live leg:
 *
 *   - the estate back chip (hud.js) actually mounts on each page
 *   - a full MBM3 transfer: code + PIN generated by the real ORBIT teacher
 *     panel, imported into the real hub — wrong PIN first (rejected, and the
 *     portfolio provably does not grow), right PIN second (record appears)
 *
 * It is deliberately an addition, not an edit to the merge gate: the estate's
 * change boundary holds modifications to an enumerated list, and this pass does
 * not widen that list — additions are the sanctioned route for new coverage.
 *
 *   node tools/stealth_live_drive.mjs --base https://madebymatt.uk/Matt-s-Apps-/
 *   node tools/stealth_live_drive.mjs --base http://127.0.0.1:PORT/Matt-s-Apps-/
 */
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const pw = (() => {
  for (const p of ['playwright', '/opt/node22/lib/node_modules/playwright/index.js']) {
    try { return require(p); } catch (_) {}
  }
  console.error('[FAIL] playwright not found'); process.exit(2);
})();
const { chromium } = pw;

const argv = process.argv.slice(2);
const val = (n) => { const i = argv.indexOf(n); return i > -1 ? argv[i + 1] : null; };
const BASE = (val('--base') || process.env.MBM_BASE_URL || '').replace(/\/?$/, '/');
if (!BASE) { console.error('usage: --base <url ending in /Matt-s-Apps-/>'); process.exit(2); }

const results = [];
let group = '';
const g = (n) => { group = n; console.log(`\n${n}`); };
const check = (limb, ok, detail) => {
  results.push({ group, limb, ok });
  console.log(`  ${ok ? 'PASS' : 'FAIL'}  ${String(limb).padEnd(46)} ${detail}`);
  return ok;
};

const browser = await chromium.launch({
  args: ['--use-gl=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'],
});

async function newPage(vw = { width: 390, height: 844 }, perms = []) {
  const ctx = await browser.newContext({
    viewport: vw,
    permissions: perms,
  });
  const page = await ctx.newPage();
  const errs = [];
  page.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
  page.on('pageerror', (e) => errs.push('pageerror: ' + e.message));
  return { ctx, page, errs };
}

async function splashOnceAndSkip(page, file) {
  await page.goto(new URL(file, BASE).href, { waitUntil: 'domcontentloaded' });
  let everVisible = false;
  for (let t = 0; t < 30; t++) {
    const up = await page.evaluate(() => {
      const el = document.querySelector('.mbm-splash');
      if (!el) return false;
      const cs = getComputedStyle(el);
      return cs.display !== 'none' && cs.visibility !== 'hidden' && Number(cs.opacity) > 0.05;
    }).catch(() => false);
    if (up) { everVisible = true; break; }
    await page.waitForTimeout(120);
  }
  check(`${file}: splash renders on the origin`, everVisible, everVisible ? 'visible' : 'never appeared');
  const skip = await page.$('.mbm-splash .mbm-skip');
  if (skip) {
    await skip.click().catch(() => {});
    await page.waitForTimeout(800);
  }
  const gone = await page.evaluate(() => !document.querySelector('.mbm-splash'));
  check(`${file}: Skip closes it`, gone, gone ? 'closed' : 'still up');
}

async function backChip(page, file) {
  // hud.js mounts its dock/back chip asynchronously; poll for any hud mount.
  let found = null;
  for (let t = 0; t < 25; t++) {
    found = await page.evaluate(() => {
      // hud.js namespaces everything under "mbmhud": the back/home chips and
      // the dock pill. Any one of them visible = the estate chrome mounted.
      const el = document.querySelector('#mbmhud-back, #mbmhud-home, #mbmhud-pill');
      if (!el) return null;
      const cs = getComputedStyle(el);
      if (cs.display === 'none' || cs.visibility === 'hidden') return null;
      const b = el.getBoundingClientRect();
      if (b.width <= 0 || b.height <= 0) return null;
      return { sel: el.id, w: Math.round(b.width), h: Math.round(b.height) };
    }).catch(() => null);
    if (found) break;
    await page.waitForTimeout(200);
  }
  check(`${file}: estate back chip (hud.js) mounts`, !!found,
    found ? `${found.sel} ${found.w}x${found.h}` : 'no hud mount found');
}

/* ---------------------------------------------------------------- pages */
g('splash once + Skip + back chip, per page, on the base under test');
console.log(`  base: ${BASE}`);
for (const file of ['orbit-vector-diagnostic.html', 'enzyme-reactor-overdrive.html', 'mbm-master-hub.html']) {
  const { ctx, page, errs } = await newPage();
  await splashOnceAndSkip(page, file);
  await backChip(page, file);
  check(`${file}: console clean`, errs.length === 0, errs.length ? JSON.stringify(errs.slice(0, 2)) : 'no errors');
  await ctx.close();
}

/* --------------------------------------------------- hub frames + READY */
g('hub Lesson Deck: both frames READY, no second splash');
{
  const { ctx, page, errs } = await newPage({ width: 1280, height: 1000 });
  await page.goto(new URL('mbm-master-hub.html', BASE).href, { waitUntil: 'domcontentloaded' });
  await page.waitForTimeout(4200);
  await page.evaluate(async () => {
    for (const b of [...document.querySelectorAll('button,a,[role="tab"],[data-view]')]
      .filter((x) => /lesson|deck/i.test(x.textContent || x.getAttribute('data-view') || ''))) {
      try { b.click(); } catch (_) {}
    }
    await new Promise((r) => setTimeout(r, 3000));
  });
  const status = await page.evaluate(() => ({
    orbit: (document.querySelector('#orbitFrameStatus') || {}).textContent || '',
    enzyme: (document.querySelector('#enzymeFrameStatus') || {}).textContent || '',
  }));
  check('both frames READY v4.0', /READY\s*v?4\.0/i.test(status.orbit) && /READY\s*v?4\.0/i.test(status.enzyme),
    `orbit=${JSON.stringify(status.orbit)} enzyme=${JSON.stringify(status.enzyme)}`);
  let framedSplash = 0, reads = 0;
  for (let t = 0; t < 12; t++) {
    for (const fr of page.frames()) {
      if (fr === page.mainFrame()) continue;
      const r = await fr.evaluate(() => !!document.querySelector('.mbm-splash')).catch(() => null);
      if (r === null) continue;
      reads++; if (r) framedSplash++;
    }
    await page.waitForTimeout(200);
  }
  check('no splash inside either frame', reads > 0 && framedSplash === 0, `${reads} frame read(s), ${framedSplash} splash(es)`);
  check('hub console clean', errs.length === 0, errs.length ? JSON.stringify(errs.slice(0, 2)) : 'clean');
  await ctx.close();
}

/* ------------------------------------- MBM3: real code, wrong PIN, right PIN */
g('MBM3 transfer: ORBIT teacher panel -> hub import, wrong PIN then right');
{
  const { ctx: octx, page: orbit } = await newPage({ width: 1024, height: 900 }, ['clipboard-read', 'clipboard-write']);
  await orbit.goto(new URL('orbit-vector-diagnostic.html', BASE).href, { waitUntil: 'domcontentloaded' });
  await orbit.waitForTimeout(4000);
  await orbit.evaluate(() => { const s = document.querySelector('.mbm-splash'); if (s) s.remove(); });
  // The teacher panel is deliberately unlabelled: Alt+Shift+D.
  await orbit.keyboard.press('Alt+Shift+D');
  await orbit.waitForSelector('#teacherDialog[open]', { timeout: 8000 }).catch(() => {});
  await orbit.waitForFunction(() =>
    /QR \d+×\d+|UNENCRYPTED/i.test((document.querySelector('#transferStatus') || {}).textContent || ''),
    { timeout: 15000 }).catch(() => {});
  const gen = await orbit.evaluate(() => ({
    status: (document.querySelector('#transferStatus') || {}).textContent || '',
    pin: ((document.querySelector('#transferPin') || {}).textContent || '').replace(/\s+/g, ''),
  }));
  const modules = (gen.status.match(/QR (\d+)×(\d+)/) || [])[1];
  check('ORBIT teacher panel generates the bundle', /MBM3/.test(gen.status),
    gen.status.slice(0, 90));
  check('encrypted QR renders at 33×33 modules', modules === '33',
    `status reports QR ${modules || '?'}×${modules || '?'} (A-P4 spec: 33×33)`);
  check('a six-digit PIN is issued', /^\d{6}$/.test(gen.pin), `pin ${gen.pin ? gen.pin.replace(/\d/g, '•') : '(none)'}`);
  await orbit.click('#copyTransferBtn').catch(() => {});
  await orbit.waitForTimeout(600);
  const code = await orbit.evaluate(() => navigator.clipboard.readText()).catch(() => '');
  check('the real transfer code was captured', /^MBM3U?\./.test(code), `${code.slice(0, 12)}… (${code.length} chars)`);
  await octx.close();

  const { ctx: hctx, page: hub } = await newPage({ width: 1024, height: 900 });
  await hub.goto(new URL('mbm-master-hub.html', BASE).href, { waitUntil: 'domcontentloaded' });
  await hub.waitForTimeout(4200);
  await hub.evaluate(() => { const s = document.querySelector('.mbm-splash'); if (s) s.remove(); });
  // The import panel lives behind the hub's own tab bar.
  await hub.click('[data-view="import"]').catch(() => {});
  await hub.waitForSelector('#transferCode', { state: 'visible', timeout: 8000 });
  const countRecords = () => hub.evaluate(() => {
    try { return (JSON.parse(localStorage.getItem('mbm_master_portfolio_v1') || '{}').records || []).length; }
    catch (_) { return -1; }
  });
  const before = await countRecords();
  const wrongPin = gen.pin === '000000' ? '111111' : '000000';
  await hub.fill('#transferCode', code);
  if (/^MBM3\./.test(code)) {
    await hub.fill('#transferPinInput', wrongPin);
    await hub.click('#decodeBtn');
    await hub.waitForFunction(() => /Import failed|Imported/.test((document.querySelector('#decodeResult') || {}).textContent || ''), { timeout: 15000 }).catch(() => {});
    const r1 = await hub.evaluate(() => (document.querySelector('#decodeResult') || {}).textContent || '');
    const afterWrong = await countRecords();
    check('wrong PIN is rejected', /Import failed/i.test(r1), r1.slice(0, 80));
    check('…and adds NO record', afterWrong === before, `records ${before} -> ${afterWrong}`);
  } else {
    check('wrong PIN leg', true, 'code is MBM3U (unencrypted offline mode) — no PIN to get wrong; leg not applicable, stated rather than skipped silently');
  }
  await hub.fill('#transferPinInput', gen.pin);
  await hub.click('#decodeBtn');
  await hub.waitForFunction(() => /Imported/i.test((document.querySelector('#decodeResult') || {}).textContent || ''), { timeout: 20000 }).catch(() => {});
  const r2 = await hub.evaluate(() => (document.querySelector('#decodeResult') || {}).textContent || '');
  const after = await countRecords();
  check('right PIN imports', /Imported/i.test(r2), r2.slice(0, 80));
  check('…and the portfolio grows by one', after === before + 1, `records ${before} -> ${after}`);
  await hctx.close();
}

await browser.close();
const failed = results.filter((r) => !r.ok);
console.log(`\n${results.length - failed.length}/${results.length} limbs pass`);
if (failed.length) { console.log('[FAIL] live drive:'); for (const f of failed) console.log(`   - ${f.group} / ${f.limb}`); process.exit(1); }
console.log('[PASS] live drive: splash once + Skip + back chip on every page, both frames READY '
  + 'with no framed splash, and a real MBM3 code round-trips — wrong PIN rejected without a '
  + 'record, right PIN imports exactly one');
