#!/usr/bin/env node
/* The B4 import matrix, every row a gate, in a real browser on the built bytes.
 *
 * The bridge's whole claim is routing: WAVE/OHM envelopes decode, the four
 * original formats reach the original decoder untouched, garbage still dies at
 * the gates it dies at today. Static checks proved the text of that claim;
 * this proves the behaviour, with codes generated by the REAL published apps'
 * own UI — not synthetic strings — for every WAVE/OHM row.
 *
 * The artwork rows deserve one honest sentence: WAVE and OHM export no SVG
 * artwork (measured — zero mbm-eval producers in either app), so the SVG in
 * those rows is a carrier constructed around a REAL app-generated code. The
 * route under test is the hub's artwork importer; the code inside it is real.
 *
 *   node tools/verify_wave_ohm_bridge.mjs --base http://127.0.0.1:PORT/Matt-s-Apps-/
 */
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const pw = (() => {
  for (const p of ['playwright', '/opt/node22/lib/node_modules/playwright/index.js']) {
    try { return require(p); } catch (_) {}
  }
  console.error('[FAIL] playwright not found'); process.exit(2);
})();
const { chromium } = pw;

const argv = process.argv.slice(2);
const val = (n) => { const i = argv.indexOf(n); return i > -1 ? argv[i + 1] : null; };
const BASE = (val('--base') || process.env.MBM_BASE_URL || '').replace(/\/?$/, '/');
if (!BASE) { console.error('usage: --base <url>'); process.exit(2); }

const results = [];
let group = '';
const g = (n) => { group = n; console.log(`\n${n}`); };
const check = (limb, ok, detail) => {
  results.push({ group, limb, ok });
  console.log(`  ${ok ? 'PASS' : 'FAIL'}  ${String(limb).padEnd(52)} ${detail}`);
  return ok;
};

const browser = await chromium.launch({
  args: ['--use-gl=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'],
});
const ctx = await browser.newContext({ viewport: { width: 1280, height: 1000 } });

async function open(file) {
  const page = await ctx.newPage();
  const errs = [];
  page.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
  page.on('pageerror', (e) => errs.push('pageerror: ' + e.message));
  await page.goto(new URL(file, BASE).href, { waitUntil: 'domcontentloaded' });
  await page.waitForTimeout(1200);
  await page.evaluate(() => { const s = document.querySelector('.mbm-splash'); if (s) s.remove(); });
  return { page, errs };
}

/* A real code from a real app: open its QR modal, choose the code payload,
   read the readonly payload field the app itself fills. */
async function appCode(file, mutate = false) {
  const { page } = await open(file);
  if (mutate) {
    // The hub fingerprints records and DEDUPES identical evidence — correctly.
    // The first artwork attempt re-imported the very payload the paste row had
    // already recorded, and the hub declined the duplicate; that was the hub
    // working, not the route failing. A range-input nudge did not reach the
    // payload either — WAVE's compactQrState captures mode/preset/tone fields,
    // not raw slider positions mid-gesture. So: WAVE flips its real mode
    // switch (m: 0 -> 1 in the encoded state); OHM simply uses its 'state'
    // payload where the paste row used 'result' — a different envelope kind.
    await page.click('#modeWave').catch(() => {});
    await page.waitForTimeout(700);
  }
  await page.click('#qrBtn');
  await page.waitForSelector('#qrPayloadField', { timeout: 8000 });
  // Select by VALUE, not index: WAVE offers [state, link]; OHM offers
  // [state, result, link]. Paste rows take the richest envelope (result where
  // it exists, else state); artwork rows take 'state'.
  const want = mutate ? 'state' : 'result';
  await page.selectOption('#qrPayloadType', want).catch(() => {});
  await page.waitForTimeout(500);
  let code = (await page.inputValue('#qrPayloadField')).trim();
  if (!/^MBM\./.test(code)) {
    await page.selectOption('#qrPayloadType', 'state').catch(() => {});
    await page.waitForTimeout(500);
    code = (await page.inputValue('#qrPayloadField')).trim();
  }
  // leave state behind for scanKnownStorage: the apps autosave under their key
  await page.waitForTimeout(600);
  await page.close();
  return code;
}

async function hubPage() {
  const { page, errs } = await open('mbm-master-hub.html');
  await page.click('[data-view="import"]');
  await page.waitForSelector('#transferCode', { state: 'visible', timeout: 8000 });
  return { hub: page, errs };
}
const records = (hub) => hub.evaluate(() => {
  try { return (JSON.parse(localStorage.getItem('mbm_master_portfolio_v1') || '{}').records || []).length; }
  catch (_) { return -1; }
});
async function pasteImport(hub, code, pin = '') {
  await hub.fill('#transferCode', code);
  await hub.fill('#transferPinInput', pin);
  await hub.evaluate(() => { document.querySelector('#decodeResult').textContent = ''; });
  await hub.click('#decodeBtn');
  // decodeImport writes a transient 'Decrypting locally…' first; sampling on
  // any non-empty text returned that placeholder and let the real import land
  // AFTER the record counts were read — every downstream count then drifted.
  // Wait for the FINAL states only.
  await hub.waitForFunction(() =>
    /Imported|Import failed/i.test((document.querySelector('#decodeResult') || {}).textContent || ''), { timeout: 20000 });
  return hub.evaluate(() => (document.querySelector('#decodeResult') || {}).textContent || '');
}

/* ------------------------------------------------- 1. real WAVE + OHM codes */
g('paste route: real app-generated envelopes');
const waveCode = await appCode('wave-interference-iridescence-engine-v2-3.html');
check('WAVE app hands over a real MBM.WAVE.* code', /^MBM\.WAVE\./.test(waveCode),
  `${waveCode.slice(0, 16)}… (${waveCode.length} chars)`);
const ohmCode = await appCode('ohms-law-fault-finder-v2-3.html');
check('OHM app hands over a real MBM.OHM.* code', /^MBM\.OHM\./.test(ohmCode),
  `${ohmCode.slice(0, 16)}… (${ohmCode.length} chars)`);

const { hub, errs: hubErrs } = await hubPage();
{
  const before = await records(hub);
  const r = await pasteImport(hub, waveCode);
  const after = await records(hub);
  check('WAVE envelope imports as a record', /Imported/i.test(r) && after === before + 1,
    `${r.slice(0, 60)} | records ${before} -> ${after}`);
}
{
  const before = await records(hub);
  const r = await pasteImport(hub, ohmCode);
  const after = await records(hub);
  check('OHM envelope imports as a record', /Imported/i.test(r) && after === before + 1,
    `${r.slice(0, 60)} | records ${before} -> ${after}`);
}

/* ---------------------------------------- 2. security labels stay honest */
g('security labels: WAVE/OHM records are unencrypted and stored as such');
{
  const sec = await hub.evaluate(() => {
    const rs = (JSON.parse(localStorage.getItem('mbm_master_portfolio_v1') || '{}').records || []);
    return rs.slice(-2).map((r) => JSON.stringify(r).match(/"security"\s*:\s*({[^}]*}|"[^"]*")/)?.[1] || '(none stored)');
  });
  check('stored security fields do not claim encryption', sec.every((s) => !/(encrypted"?\s*:\s*true|"encrypted")/.test(s) || /unencrypted|encoded|false/.test(s)),
    sec.join(' | ').slice(0, 110));
}

/* --------------------------------- 3. original formats reach original logic */
g('original routes preserved (MBM3 real; MBM2/MBM1 synthetic fixtures)');
{
  // real MBM3 from ORBIT (published Part A page on the same mount)
  const orbit = await ctx.newPage();
  await orbit.goto(new URL('orbit-vector-diagnostic.html', BASE).href, { waitUntil: 'domcontentloaded' });
  await orbit.waitForTimeout(3500);
  await orbit.evaluate(() => { const s = document.querySelector('.mbm-splash'); if (s) s.remove(); });
  await orbit.keyboard.press('Alt+Shift+D');
  await orbit.waitForFunction(() => /MBM3/.test((document.querySelector('#transferStatus') || {}).textContent || ''), { timeout: 15000 });
  const pin = (await orbit.evaluate(() => (document.querySelector('#transferPin') || {}).textContent || '')).replace(/\s+/g, '');
  const ctx2 = await browser.newContext({ permissions: ['clipboard-read', 'clipboard-write'] });
  // clipboard needs its own permissioned context: re-generate there
  const o2 = await ctx2.newPage();
  await o2.goto(new URL('orbit-vector-diagnostic.html', BASE).href, { waitUntil: 'domcontentloaded' });
  await o2.waitForTimeout(3500);
  await o2.evaluate(() => { const s = document.querySelector('.mbm-splash'); if (s) s.remove(); });
  await o2.keyboard.press('Alt+Shift+D');
  await o2.waitForFunction(() => /MBM3/.test((document.querySelector('#transferStatus') || {}).textContent || ''), { timeout: 15000 });
  const pin2 = (await o2.evaluate(() => (document.querySelector('#transferPin') || {}).textContent || '')).replace(/\s+/g, '');
  await o2.click('#copyTransferBtn');
  await o2.waitForTimeout(500);
  const mbm3 = await o2.evaluate(() => navigator.clipboard.readText());
  await ctx2.close(); await orbit.close();

  const wrong = pin2 === '000000' ? '111111' : '000000';
  const before = await records(hub);
  const r1 = await pasteImport(hub, mbm3, wrong);
  const mid = await records(hub);
  check('MBM3 wrong PIN still rejected, no record', /Import failed/i.test(r1) && mid === before,
    `${r1.slice(0, 60)} | ${before} -> ${mid}`);
  const r2 = await pasteImport(hub, mbm3, pin2);
  const after = await records(hub);
  check('MBM3 right PIN still imports through the ORIGINAL decoder', /Imported/i.test(r2) && after === mid + 1,
    `${r2.slice(0, 60)} | ${mid} -> ${after}`);

  // MBM2/MBM1: synthetic fixtures — assert the ROUTE by the error's identity:
  // both must fall through the bridge to the original decoder and fail INSIDE
  // it (decrypt/decode wording), never at the unrecognised-prefix gate.
  for (const [label, fixture] of [['MBM2', 'MBM2.AAAABBBBCCCCDDDD'], ['MBM1', 'MBM1.AAAABBBBCCCCDDDD']]) {
    const b = await records(hub);
    const r = await pasteImport(hub, fixture, '123456');
    const a = await records(hub);
    check(`${label} fixture routes to the original decoder`,
      /Import failed/i.test(r) && !/Unrecognised transfer-code prefix/i.test(r) && a === b,
      `${r.slice(0, 76)} | records unchanged: ${a === b}`);
  }

  // garbage prefix: must still die with the original unrecognised error
  const b2 = await records(hub);
  const rg = await pasteImport(hub, 'XYZ.NOT-A-REAL-CODE', '');
  const a2 = await records(hub);
  check('garbage prefix still dies at the original gate', /Unrecognised/i.test(rg) && a2 === b2,
    `${rg.slice(0, 70)}`);
}

/* --------------------------------------------------- 4. the artwork route */
g('artwork route: real codes carried in SVG metadata#mbm-eval');
{
  const mkSvg = (code) =>
    `<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10">` +
    `<metadata id="mbm-eval">${code}</metadata><rect width="10" height="10"/></svg>`;
  const waveArt = await appCode('wave-interference-iridescence-engine-v2-3.html', true);
  const ohmArt = await appCode('ohms-law-fault-finder-v2-3.html', true);
  check('artwork codes are distinct real envelopes', waveArt !== waveCode && ohmArt !== ohmCode,
    `wave ${waveArt.length} chars vs paste ${waveCode.length}; ohm ${ohmArt.length} vs ${ohmCode.length}`);
  // The hub fingerprints evidence as app|count|profile|stats. WAVE's only
  // text-surfaced envelope is the compact STATE, whose radar mapping is the
  // same flat profile for every state — so any second WAVE state import
  // fingerprints identically and dedupes. That is the hub's own policy, not a
  // route defect, and it is asserted as such below. The artwork route is
  // therefore proven on a FRESH portfolio. Removing the storage key and
  // reloading does NOT produce one — the hub flushes its in-memory state on
  // unload and resurrects the key — so fresh means a fresh browser context.
  // The original context stays open: the scan group needs the app autosaves
  // living in ITS storage.
  const ctxB = await browser.newContext({ viewport: { width: 1280, height: 1000 } });
  const hub2 = await ctxB.newPage();
  await hub2.goto(new URL('mbm-master-hub.html', BASE).href, { waitUntil: 'domcontentloaded' });
  await hub2.waitForTimeout(1500);
  await hub2.evaluate(() => { const s = document.querySelector('.mbm-splash'); if (s) s.remove(); });
  await hub2.click('[data-view="import"]');
  await hub2.waitForSelector('#transferCode', { state: 'visible', timeout: 8000 });
  for (const [label, code] of [['WAVE', waveArt], ['OHM', ohmArt]]) {
    const before = await records(hub2);
    await hub2.setInputFiles('#artInput', {
      name: `${label.toLowerCase()}-evidence.svg`, mimeType: 'image/svg+xml',
      buffer: Buffer.from(mkSvg(code), 'utf-8'),
    });
    await hub2.waitForFunction(() =>
      /record/i.test((document.querySelector('#artResult') || {}).textContent || ''), { timeout: 15000 });
    const res = await hub2.evaluate(() => (document.querySelector('#artResult') || {}).textContent || '');
    const after = await records(hub2);
    check(`${label} code imports through the ARTWORK route`, after === before + 1,
      `${res.split('\n')[0].slice(0, 66)} | records ${before} -> ${after}`);
  }
  // the dedupe itself, asserted rather than tripped over: the same real WAVE
  // code a second time must add exactly nothing
  {
    const b = await records(hub2);
    await hub2.setInputFiles('#artInput', {
      name: 'wave-duplicate.svg', mimeType: 'image/svg+xml',
      buffer: Buffer.from(mkSvg(waveArt), 'utf-8'),
    });
    await hub2.waitForFunction(() =>
      ((document.querySelector('#artResult') || {}).textContent || '').length > 0, { timeout: 15000 });
    const a = await records(hub2);
    check('duplicate evidence dedupes to zero (hub fingerprint policy)', a === b,
      `records ${b} -> ${a}`);
  }
  // garbage prefix in artwork must fail at the same widened gate, same message
  const before = await records(hub2);
  await hub2.setInputFiles('#artInput', {
    name: 'garbage.svg', mimeType: 'image/svg+xml',
    buffer: Buffer.from(mkSvg('XYZ.GARBAGE'), 'utf-8'),
  });
  await hub2.waitForFunction(() =>
    ((document.querySelector('#artResult') || {}).textContent || '').length > 0, { timeout: 15000 });
  const res = await hub2.evaluate(() => (document.querySelector('#artResult') || {}).textContent || '');
  const after = await records(hub2);
  check('garbage artwork still fails at the pre-gate', /unsupported format/i.test(res) && after === before,
    res.replace(/\n/g, ' | ').slice(0, 90));
  await ctxB.close();
}

/* -------------------------------- 5. scanKnownStorage over HTTP, same origin */
g('scanKnownStorage: same-origin discovery of app autosaves');
{
  const found = await hub.evaluate(() => {
    const rs = window.MBMTeacherToolsBridge ? window.MBMTeacherToolsBridge.scanKnownStorage() : null;
    return rs ? rs.map((r) => r.key) : null;
  });
  check('bridge is reachable in the hub page', Array.isArray(found), found === null ? 'window.MBMTeacherToolsBridge missing' : `${found.length} record(s)`);
  if (Array.isArray(found)) {
    check('finds the WAVE autosave', found.includes('mbm_wave_iridescence_v2'), found.join(', ') || '(none)');
    check('finds the OHM autosave', found.includes('mbm_ohms_fault_finder_v2'), '');
  }
}
check('hub console clean through the whole matrix', hubErrs.length === 0,
  hubErrs.length ? JSON.stringify(hubErrs.slice(0, 3)) : 'no errors');

await browser.close();
const failed = results.filter((r) => !r.ok);
console.log(`\n${results.length - failed.length}/${results.length} rows pass`);
if (failed.length) { console.log('[FAIL] B4 matrix:'); for (const f of failed) console.log(`   - ${f.group} / ${f.limb}`); process.exit(1); }
console.log('[PASS] B4 matrix: real WAVE/OHM envelopes import by paste and by artwork, MBM3 '
  + 'wrong/right PIN behave exactly as before, MBM2/MBM1 fixtures fail inside the original '
  + 'decoder rather than at the prefix gate, garbage dies where it always died, and the '
  + 'bridge discovers both app autosaves same-origin');
